import { ArrowRight, BarChart3, BookOpenCheck, CheckCircle2, Clock3, Laptop, Layers3, Target } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEO, organizationSchema } from '../components/SEO';
import { Container, ExternalButton, InternalButton, SectionTitle } from '../components/UI';
import { platformConfig } from '../config/platform';
import { examCategories, popularExams } from '../data/exams';

const benefits = [{icon:Laptop,title:'Exam-like interface',text:'Practise in a focused digital environment through the Testpress platform.'},{icon:BarChart3,title:'Detailed performance analysis',text:'Review results and use performance signals to guide the next study session.'},{icon:BookOpenCheck,title:'Quality mock tests',text:'Build preparation around structured tests for your chosen examination.'},{icon:Clock3,title:'Accessible anywhere',text:'Continue preparation across compatible phones, tablets and computers.'},{icon:Layers3,title:'Structured preparation',text:'Move from subject practice to full-length mocks with a clear purpose.'}];

export function Home() { return <>
  <SEO title="ExpressMock — Prepare Smarter. Perform Better." description="Explore structured mock tests and preparation resources for banking, SSC, railway, insurance, regulatory and state-level examinations." schema={organizationSchema}/>
  <section className="relative overflow-hidden bg-brand-950 py-16 text-white sm:py-24"><div className="hero-grid absolute inset-0 opacity-30"/><Container className="relative grid items-center gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-blue-300/20 bg-white/5 px-4 py-2 text-sm text-blue-100"><Target size={16}/> Preparation with purpose</p><h1 className="mt-6 max-w-3xl text-5xl font-bold tracking-tight sm:text-6xl">Prepare smarter.<br/><span className="text-blue-300">Perform better.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">ExpressMock helps aspirants discover high-quality mock tests and practical preparation resources for Indian competitive examinations—without noise or exaggerated promises.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><InternalButton to="/test-series" variant="light">Explore Mock Tests <ArrowRight size={18}/></InternalButton><ExternalButton href={platformConfig.studentLoginUrl} variant="secondary" className="border-slate-500 text-white hover:bg-white/10">Student Login</ExternalButton></div></div><div className="rounded-3xl border border-white/10 bg-white p-5 text-brand-900 shadow-2xl sm:p-7"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><p className="text-sm font-semibold text-brand-500">Preparation workspace</p><p className="mt-1 text-xl font-bold">Practise. Review. Improve.</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50"><BarChart3/></span></div><div className="mt-5 grid gap-3">{['Choose the right examination','Attempt focused mock tests','Review performance thoughtfully'].map((text,i)=><div key={text} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-brand-900 text-sm font-bold text-white">{i+1}</span><span className="font-medium">{text}</span></div>)}</div></div></Container></section>
  <section className="section"><Container><SectionTitle eyebrow="Explore by category" title="Preparation for the exam you choose">Browse clear pathways into popular competitive-exam categories.</SectionTitle><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{examCategories.map(category=><Link to={`/exams?category=${encodeURIComponent(category.name)}`} key={category.name} className="card group"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><BookOpenCheck/></span><ArrowRight className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-brand-600"/></div><h3 className="mt-5 text-xl font-bold text-brand-900">{category.name}</h3><p className="mt-2 leading-7 text-slate-600">{category.description}</p></Link>)}</div></Container></section>
  <section className="section bg-slate-50"><Container><SectionTitle eyebrow="Popular exams" title="Start with a focused exam page">Understand the preparation scope, then move to available tests on Testpress.</SectionTitle><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{popularExams.map(exam=><Link className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:shadow-soft" key={exam.slug} to={`/exams/${exam.slug}`}><p className="text-sm font-semibold text-brand-500">{exam.category}</p><h3 className="mt-2 text-xl font-bold text-brand-900">{exam.shortName}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{exam.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-600">View exam guide <ArrowRight size={16}/></span></Link>)}</div></Container></section>
  <section className="section"><Container><SectionTitle eyebrow="Why ExpressMock" title="Tools that support deliberate practice">The platform experience is designed around practical preparation—not vanity metrics.</SectionTitle><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-5">{benefits.map(({icon:Icon,title,text})=><div key={title}><span className="grid h-12 w-12 place-items-center rounded-xl bg-brand-900 text-white"><Icon/></span><h3 className="mt-5 font-bold text-brand-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></Container></section>
  <section className="section bg-brand-50"><Container><SectionTitle eyebrow="How it works" title="From choosing an exam to learning from results"/><ol className="mt-10 grid gap-4 md:grid-cols-5">{['Select your exam','Choose a test series','Sign in on Testpress','Attempt the mock test','Review your performance'].map((step,index)=><li key={step} className="relative rounded-2xl bg-white p-5 shadow-sm"><span className="text-sm font-bold text-brand-500">STEP {index+1}</span><p className="mt-3 font-bold text-brand-900">{step}</p></li>)}</ol></Container></section>
  <section className="section"><Container><div className="overflow-hidden rounded-3xl bg-brand-900 px-6 py-12 text-center text-white sm:px-12"><CheckCircle2 className="mx-auto text-blue-300" size={36}/><h2 className="mt-5 text-3xl font-bold">Start your preparation</h2><p className="mx-auto mt-3 max-w-xl text-slate-300">Explore the student platform to view currently available tests, plan details and access options.</p><div className="mt-7"><ExternalButton href={platformConfig.studentLoginUrl} variant="light">Open student platform</ExternalButton></div></div></Container></section>
  </>; }
